version: '3'

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: psicoid-app
    ports:
      - "3333:3333"
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    build: .docker/postgres
    container_name: psicoid-db
    image: postgres
    restart: always
    tty: true
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=psicoid
    ports:
      - "5432:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
  redis:
    image: redis
    container_name: psicoid_redis
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - PASSWORD=cNTlvgtCCqhIA1JzpHXXmCKvvjwgPrQZ
    ports:
      - 17830:17830
  